// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtuTFK_8oF99pCIIwIc9YOMqFBf-Cs530',
    appId: '1:484830733505:web:7070fe1da14d88eea46040',
    messagingSenderId: '484830733505',
    projectId: 'fillahub-897d6',
    authDomain: 'fillahub-897d6.firebaseapp.com',
    databaseURL: 'https://fillahub-897d6-default-rtdb.firebaseio.com',
    storageBucket: 'fillahub-897d6.appspot.com',
    measurementId: 'G-MXV885HEDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe-5K7te2zJgCwub62T12FkAYEWF3B_ps',
    appId: '1:484830733505:android:5e5d43e5943cdbdea46040',
    messagingSenderId: '484830733505',
    projectId: 'fillahub-897d6',
    databaseURL: 'https://fillahub-897d6-default-rtdb.firebaseio.com',
    storageBucket: 'fillahub-897d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvwNgHxP3IwZLRsbtegX4bbAD8H58htH0',
    appId: '1:484830733505:ios:801eb814c886f8b3a46040',
    messagingSenderId: '484830733505',
    projectId: 'fillahub-897d6',
    databaseURL: 'https://fillahub-897d6-default-rtdb.firebaseio.com',
    storageBucket: 'fillahub-897d6.appspot.com',
    iosBundleId: 'com.example.fillahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvwNgHxP3IwZLRsbtegX4bbAD8H58htH0',
    appId: '1:484830733505:ios:801eb814c886f8b3a46040',
    messagingSenderId: '484830733505',
    projectId: 'fillahub-897d6',
    databaseURL: 'https://fillahub-897d6-default-rtdb.firebaseio.com',
    storageBucket: 'fillahub-897d6.appspot.com',
    iosBundleId: 'com.example.fillahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtuTFK_8oF99pCIIwIc9YOMqFBf-Cs530',
    appId: '1:484830733505:web:dff4b6cb44b6414ea46040',
    messagingSenderId: '484830733505',
    projectId: 'fillahub-897d6',
    authDomain: 'fillahub-897d6.firebaseapp.com',
    databaseURL: 'https://fillahub-897d6-default-rtdb.firebaseio.com',
    storageBucket: 'fillahub-897d6.appspot.com',
    measurementId: 'G-DE5NKJE3Q4',
  );
}
